package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/joseph-beck/aircraft-departure-simulator/ads-backend/generated/sqlc"
	"github.com/joseph-beck/aircraft-departure-simulator/ads-backend/pkg/carrier/fleet/aircraft/subtype/maxweight"
)

type DB struct {
	// Context for DB operations.
	ctx context.Context
	// Postgres database connection.
	conn *pgx.Conn
	// Queries generated by sqlc.
	queries *sqlc.Queries
}

func NewDB(conn Connecter) *DB {
	db, err := conn.Connect()
	if err != nil {
		panic(err)
	}

	return &db
}

func (db *DB) GetMaximumWeights() ([]maxweight.MaxWeight, error) {
	data, err := db.queries.GetMaximumWeights(db.ctx)
	if err != nil {
		return nil, err
	}

	var maxWeights []maxweight.MaxWeight
	preparer := maxweight.MaxWeightPreparer{}
	for _, d := range data {
		mw, err := preparer.Prepare(d)
		if err != nil {
			return nil, err
		}
		maxWeights = append(maxWeights, mw)
	}

	return maxWeights, nil
}
